# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreatePlanPage.ui'
#
# Created: Sat Nov 29 18:09:57 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CreatePlan(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setEnabled(True)
        Form.resize(719, 623)
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(-3, 130, 721, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(80, 140, 41, 481))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(130, 120, 131, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Sans Serif"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 210, 321, 321))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.radioButtonPlan = QtGui.QRadioButton(self.layoutWidget)
        self.radioButtonPlan.setObjectName(_fromUtf8("radioButtonPlan"))
        self.verticalLayout.addWidget(self.radioButtonPlan)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.checkBoxChest = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxChest.setEnabled(False)
        self.checkBoxChest.setObjectName(_fromUtf8("checkBoxChest"))
        self.verticalLayout_2.addWidget(self.checkBoxChest)
        self.checkBoxBack = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxBack.setEnabled(False)
        self.checkBoxBack.setObjectName(_fromUtf8("checkBoxBack"))
        self.verticalLayout_2.addWidget(self.checkBoxBack)
        self.checkBoxBiscep = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxBiscep.setEnabled(False)
        self.checkBoxBiscep.setObjectName(_fromUtf8("checkBoxBiscep"))
        self.verticalLayout_2.addWidget(self.checkBoxBiscep)
        self.checkTricep = QtGui.QCheckBox(self.layoutWidget)
        self.checkTricep.setEnabled(False)
        self.checkTricep.setObjectName(_fromUtf8("checkTricep"))
        self.verticalLayout_2.addWidget(self.checkTricep)
        self.checkBoxLegs = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxLegs.setEnabled(False)
        self.checkBoxLegs.setObjectName(_fromUtf8("checkBoxLegs"))
        self.verticalLayout_2.addWidget(self.checkBoxLegs)
        self.checkBoxCore = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxCore.setEnabled(False)
        self.checkBoxCore.setObjectName(_fromUtf8("checkBoxCore"))
        self.verticalLayout_2.addWidget(self.checkBoxCore)
        self.checkBoxShoulders = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxShoulders.setEnabled(False)
        self.checkBoxShoulders.setObjectName(_fromUtf8("checkBoxShoulders"))
        self.verticalLayout_2.addWidget(self.checkBoxShoulders)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setEnabled(False)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.checkBoxChest_2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxChest_2.setEnabled(False)
        self.checkBoxChest_2.setObjectName(_fromUtf8("checkBoxChest_2"))
        self.verticalLayout_3.addWidget(self.checkBoxChest_2)
        self.checkBoxBack_2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxBack_2.setEnabled(False)
        self.checkBoxBack_2.setObjectName(_fromUtf8("checkBoxBack_2"))
        self.verticalLayout_3.addWidget(self.checkBoxBack_2)
        self.checkBoxBiscep_2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxBiscep_2.setEnabled(False)
        self.checkBoxBiscep_2.setObjectName(_fromUtf8("checkBoxBiscep_2"))
        self.verticalLayout_3.addWidget(self.checkBoxBiscep_2)
        self.checkTricep_2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkTricep_2.setEnabled(False)
        self.checkTricep_2.setObjectName(_fromUtf8("checkTricep_2"))
        self.verticalLayout_3.addWidget(self.checkTricep_2)
        self.checkBoxLegs_2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxLegs_2.setEnabled(False)
        self.checkBoxLegs_2.setObjectName(_fromUtf8("checkBoxLegs_2"))
        self.verticalLayout_3.addWidget(self.checkBoxLegs_2)
        self.checkBoxCore_2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxCore_2.setEnabled(False)
        self.checkBoxCore_2.setObjectName(_fromUtf8("checkBoxCore_2"))
        self.verticalLayout_3.addWidget(self.checkBoxCore_2)
        self.checkBoxShoulders_2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxShoulders_2.setEnabled(False)
        self.checkBoxShoulders_2.setObjectName(_fromUtf8("checkBoxShoulders_2"))
        self.verticalLayout_3.addWidget(self.checkBoxShoulders_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setEnabled(False)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.checkBoxChest_3 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxChest_3.setEnabled(False)
        self.checkBoxChest_3.setObjectName(_fromUtf8("checkBoxChest_3"))
        self.verticalLayout_4.addWidget(self.checkBoxChest_3)
        self.checkBoxBack_3 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxBack_3.setEnabled(False)
        self.checkBoxBack_3.setObjectName(_fromUtf8("checkBoxBack_3"))
        self.verticalLayout_4.addWidget(self.checkBoxBack_3)
        self.checkBoxBiscep_3 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxBiscep_3.setEnabled(False)
        self.checkBoxBiscep_3.setObjectName(_fromUtf8("checkBoxBiscep_3"))
        self.verticalLayout_4.addWidget(self.checkBoxBiscep_3)
        self.checkTricep_3 = QtGui.QCheckBox(self.layoutWidget)
        self.checkTricep_3.setEnabled(False)
        self.checkTricep_3.setObjectName(_fromUtf8("checkTricep_3"))
        self.verticalLayout_4.addWidget(self.checkTricep_3)
        self.checkBoxLegs_3 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxLegs_3.setEnabled(False)
        self.checkBoxLegs_3.setObjectName(_fromUtf8("checkBoxLegs_3"))
        self.verticalLayout_4.addWidget(self.checkBoxLegs_3)
        self.checkBoxCore_3 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxCore_3.setEnabled(False)
        self.checkBoxCore_3.setObjectName(_fromUtf8("checkBoxCore_3"))
        self.verticalLayout_4.addWidget(self.checkBoxCore_3)
        self.checkBoxShoulders_3 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBoxShoulders_3.setEnabled(False)
        self.checkBoxShoulders_3.setObjectName(_fromUtf8("checkBoxShoulders_3"))
        self.verticalLayout_4.addWidget(self.checkBoxShoulders_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonSubmit = QtGui.QPushButton(self.layoutWidget)
        self.pushButtonSubmit.setObjectName(_fromUtf8("pushButtonSubmit"))
        self.horizontalLayout_2.addWidget(self.pushButtonSubmit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "Create Plan", None))
        self.label_2.setText(_translate("Form", "Plan Length:", None))
        self.radioButtonPlan.setText(_translate("Form", "3 Day Plan", None))
        self.label_3.setText(_translate("Form", "Day 1:", None))
        self.checkBoxChest.setText(_translate("Form", "Chest", None))
        self.checkBoxBack.setText(_translate("Form", "Back", None))
        self.checkBoxBiscep.setText(_translate("Form", "Biscep", None))
        self.checkTricep.setText(_translate("Form", "Tricep", None))
        self.checkBoxLegs.setText(_translate("Form", "Legs", None))
        self.checkBoxCore.setText(_translate("Form", "Core(abs)", None))
        self.checkBoxShoulders.setText(_translate("Form", "Shoulders", None))
        self.label_4.setText(_translate("Form", "Day 2:", None))
        self.checkBoxChest_2.setText(_translate("Form", "Chest", None))
        self.checkBoxBack_2.setText(_translate("Form", "Back", None))
        self.checkBoxBiscep_2.setText(_translate("Form", "Biscep", None))
        self.checkTricep_2.setText(_translate("Form", "Tricep", None))
        self.checkBoxLegs_2.setText(_translate("Form", "Legs", None))
        self.checkBoxCore_2.setText(_translate("Form", "Core(abs)", None))
        self.checkBoxShoulders_2.setText(_translate("Form", "Shoulders", None))
        self.label_5.setText(_translate("Form", "Day 3:", None))
        self.checkBoxChest_3.setText(_translate("Form", "Chest", None))
        self.checkBoxBack_3.setText(_translate("Form", "Back", None))
        self.checkBoxBiscep_3.setText(_translate("Form", "Biscep", None))
        self.checkTricep_3.setText(_translate("Form", "Tricep", None))
        self.checkBoxLegs_3.setText(_translate("Form", "Legs", None))
        self.checkBoxCore_3.setText(_translate("Form", "Core(abs)", None))
        self.checkBoxShoulders_3.setText(_translate("Form", "Shoulders", None))
        self.pushButtonSubmit.setText(_translate("Form", "Submit", None))

