#Group:
#       Rechee Jozil
#       James Mark
#       Long Huynh
#       Jack Vasquez

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PyFitness(object):
    def setupUi(self, PyFitness):
        PyFitness.setObjectName(_fromUtf8("PyFitness"))
        PyFitness.resize(803, 608)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("py.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PyFitness.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(PyFitness)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.LoginWindow = QtGui.QWidget()
        self.LoginWindow.setObjectName(_fromUtf8("LoginWindow"))
        self.label_3 = QtGui.QLabel(self.LoginWindow)
        self.label_3.setGeometry(QtCore.QRect(190, 70, 391, 137))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_validation = QtGui.QLabel(self.LoginWindow)
        self.label_validation.setGeometry(QtCore.QRect(255, 410, 251, 41))
        self.label_validation.setText(_fromUtf8(""))
        self.label_validation.setWordWrap(True)
        self.label_validation.setObjectName(_fromUtf8("label_validation"))
        self.layoutWidget = QtGui.QWidget(self.LoginWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 260, 251, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.layoutWidget1 = QtGui.QWidget(self.LoginWindow)
        self.layoutWidget1.setGeometry(QtCore.QRect(340, 350, 158, 25))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.stackedWidget.addWidget(self.LoginWindow)
        self.SignUpWindow = QtGui.QWidget()
        self.SignUpWindow.setObjectName(_fromUtf8("SignUpWindow"))
        self.layoutWidget2 = QtGui.QWidget(self.SignUpWindow)
        self.layoutWidget2.setGeometry(QtCore.QRect(230, 130, 311, 171))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEditName = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditName)
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEditLastName = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEditLastName.setObjectName(_fromUtf8("lineEditLastName"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditLastName)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEditUsername = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEditUsername.setObjectName(_fromUtf8("lineEditUsername"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditUsername)
        self.label_9 = QtGui.QLabel(self.layoutWidget2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lineEditPassword = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEditPassword.setObjectName(_fromUtf8("lineEditPassword"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditPassword)
        self.label_8 = QtGui.QLabel(self.layoutWidget2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEditAge = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEditAge.setObjectName(_fromUtf8("lineEditAge"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEditAge)
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEditWeight = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEditWeight.setObjectName(_fromUtf8("lineEditWeight"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEditWeight)
        self.layoutWidget3 = QtGui.QWidget(self.SignUpWindow)
        self.layoutWidget3.setGeometry(QtCore.QRect(380, 320, 158, 25))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonSignUp = QtGui.QPushButton(self.layoutWidget3)
        self.pushButtonSignUp.setObjectName(_fromUtf8("pushButtonSignUp"))
        self.horizontalLayout_2.addWidget(self.pushButtonSignUp)
        self.pushButtonCancel = QtGui.QPushButton(self.layoutWidget3)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.label_validationSign = QtGui.QLabel(self.SignUpWindow)
        self.label_validationSign.setGeometry(QtCore.QRect(230, 360, 181, 16))
        self.label_validationSign.setText(_fromUtf8(""))
        self.label_validationSign.setObjectName(_fromUtf8("label_validationSign"))
        self.stackedWidget.addWidget(self.SignUpWindow)
        self.mainPage = QtGui.QWidget()
        self.mainPage.setObjectName(_fromUtf8("mainPage"))
        self.pushButtonProgress = QtGui.QPushButton(self.mainPage)
        self.pushButtonProgress.setGeometry(QtCore.QRect(550, 190, 211, 211))
        self.pushButtonProgress.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Stats.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButtonProgress.setIcon(icon1)
        self.pushButtonProgress.setIconSize(QtCore.QSize(235, 235))
        self.pushButtonProgress.setDefault(False)
        self.pushButtonProgress.setFlat(False)
        self.pushButtonProgress.setObjectName(_fromUtf8("pushButtonProgress"))
        self.pushButtonCreate = QtGui.QPushButton(self.mainPage)
        self.pushButtonCreate.setGeometry(QtCore.QRect(20, 190, 211, 211))
        self.pushButtonCreate.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("create.jpg")), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("create.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButtonCreate.setIcon(icon2)
        self.pushButtonCreate.setIconSize(QtCore.QSize(235, 210))
        self.pushButtonCreate.setFlat(False)
        self.pushButtonCreate.setObjectName(_fromUtf8("pushButtonCreate"))
        self.pushButtonStart = QtGui.QPushButton(self.mainPage)
        self.pushButtonStart.setGeometry(QtCore.QRect(280, 190, 211, 211))
        self.pushButtonStart.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("starter.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStart.setIcon(icon3)
        self.pushButtonStart.setIconSize(QtCore.QSize(210, 250))
        self.pushButtonStart.setObjectName(_fromUtf8("pushButtonStart"))
        self.line = QtGui.QFrame(self.mainPage)
        self.line.setGeometry(QtCore.QRect(0, 120, 791, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_10 = QtGui.QLabel(self.mainPage)
        self.label_10.setGeometry(QtCore.QRect(210, -10, 391, 137))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_29 = QtGui.QLabel(self.mainPage)
        self.label_29.setGeometry(QtCore.QRect(50, 420, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.mainPage)
        self.label_30.setGeometry(QtCore.QRect(320, 420, 141, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.mainPage)
        self.label_31.setGeometry(QtCore.QRect(570, 420, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.stackedWidget.addWidget(self.mainPage)
        self.CreatePlanWindow = QtGui.QWidget()
        self.CreatePlanWindow.setObjectName(_fromUtf8("CreatePlanWindow"))
        self.radioButtonPlan = QtGui.QRadioButton(self.CreatePlanWindow)
        self.radioButtonPlan.setGeometry(QtCore.QRect(230, 110, 317, 17))
        self.radioButtonPlan.setObjectName(_fromUtf8("radioButtonPlan"))
        self.layoutWidget4 = QtGui.QWidget(self.CreatePlanWindow)
        self.layoutWidget4.setGeometry(QtCore.QRect(470, 170, 73, 176))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_12 = QtGui.QLabel(self.layoutWidget4)
        self.label_12.setEnabled(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_4.addWidget(self.label_12)
        self.checkBoxChest_3 = QtGui.QCheckBox(self.layoutWidget4)
        self.checkBoxChest_3.setEnabled(False)
        self.checkBoxChest_3.setObjectName(_fromUtf8("checkBoxChest_3"))
        self.verticalLayout_4.addWidget(self.checkBoxChest_3)
        self.checkBoxBack_3 = QtGui.QCheckBox(self.layoutWidget4)
        self.checkBoxBack_3.setEnabled(False)
        self.checkBoxBack_3.setObjectName(_fromUtf8("checkBoxBack_3"))
        self.verticalLayout_4.addWidget(self.checkBoxBack_3)
        self.checkBoxBiscep_3 = QtGui.QCheckBox(self.layoutWidget4)
        self.checkBoxBiscep_3.setEnabled(False)
        self.checkBoxBiscep_3.setObjectName(_fromUtf8("checkBoxBiscep_3"))
        self.verticalLayout_4.addWidget(self.checkBoxBiscep_3)
        self.checkTricep_3 = QtGui.QCheckBox(self.layoutWidget4)
        self.checkTricep_3.setEnabled(False)
        self.checkTricep_3.setObjectName(_fromUtf8("checkTricep_3"))
        self.verticalLayout_4.addWidget(self.checkTricep_3)
        self.checkBoxLegs_3 = QtGui.QCheckBox(self.layoutWidget4)
        self.checkBoxLegs_3.setEnabled(False)
        self.checkBoxLegs_3.setObjectName(_fromUtf8("checkBoxLegs_3"))
        self.verticalLayout_4.addWidget(self.checkBoxLegs_3)
        self.checkBoxCore_3 = QtGui.QCheckBox(self.layoutWidget4)
        self.checkBoxCore_3.setEnabled(False)
        self.checkBoxCore_3.setObjectName(_fromUtf8("checkBoxCore_3"))
        self.verticalLayout_4.addWidget(self.checkBoxCore_3)
        self.checkBoxShoulders_3 = QtGui.QCheckBox(self.layoutWidget4)
        self.checkBoxShoulders_3.setEnabled(False)
        self.checkBoxShoulders_3.setObjectName(_fromUtf8("checkBoxShoulders_3"))
        self.verticalLayout_4.addWidget(self.checkBoxShoulders_3)
        self.layoutWidget_2 = QtGui.QWidget(self.CreatePlanWindow)
        self.layoutWidget_2.setGeometry(QtCore.QRect(350, 170, 73, 176))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_13 = QtGui.QLabel(self.layoutWidget_2)
        self.label_13.setEnabled(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_3.addWidget(self.label_13)
        self.checkBoxChest_2 = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBoxChest_2.setEnabled(False)
        self.checkBoxChest_2.setObjectName(_fromUtf8("checkBoxChest_2"))
        self.verticalLayout_3.addWidget(self.checkBoxChest_2)
        self.checkBoxBack_2 = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBoxBack_2.setEnabled(False)
        self.checkBoxBack_2.setObjectName(_fromUtf8("checkBoxBack_2"))
        self.verticalLayout_3.addWidget(self.checkBoxBack_2)
        self.checkBoxBiscep_2 = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBoxBiscep_2.setEnabled(False)
        self.checkBoxBiscep_2.setObjectName(_fromUtf8("checkBoxBiscep_2"))
        self.verticalLayout_3.addWidget(self.checkBoxBiscep_2)
        self.checkTricep_2 = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkTricep_2.setEnabled(False)
        self.checkTricep_2.setObjectName(_fromUtf8("checkTricep_2"))
        self.verticalLayout_3.addWidget(self.checkTricep_2)
        self.checkBoxLegs_2 = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBoxLegs_2.setEnabled(False)
        self.checkBoxLegs_2.setObjectName(_fromUtf8("checkBoxLegs_2"))
        self.verticalLayout_3.addWidget(self.checkBoxLegs_2)
        self.checkBoxCore_2 = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBoxCore_2.setEnabled(False)
        self.checkBoxCore_2.setObjectName(_fromUtf8("checkBoxCore_2"))
        self.verticalLayout_3.addWidget(self.checkBoxCore_2)
        self.checkBoxShoulders_2 = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBoxShoulders_2.setEnabled(False)
        self.checkBoxShoulders_2.setObjectName(_fromUtf8("checkBoxShoulders_2"))
        self.verticalLayout_3.addWidget(self.checkBoxShoulders_2)
        self.label_14 = QtGui.QLabel(self.CreatePlanWindow)
        self.label_14.setGeometry(QtCore.QRect(230, 80, 317, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.pushButtonSubmit = QtGui.QPushButton(self.CreatePlanWindow)
        self.pushButtonSubmit.setGeometry(QtCore.QRect(360, 390, 75, 23))
        self.pushButtonSubmit.setObjectName(_fromUtf8("pushButtonSubmit"))
        self.layoutWidget5 = QtGui.QWidget(self.CreatePlanWindow)
        self.layoutWidget5.setGeometry(QtCore.QRect(230, 170, 73, 176))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_11 = QtGui.QLabel(self.layoutWidget5)
        self.label_11.setEnabled(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_2.addWidget(self.label_11)
        self.checkBoxChest = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBoxChest.setEnabled(False)
        self.checkBoxChest.setObjectName(_fromUtf8("checkBoxChest"))
        self.verticalLayout_2.addWidget(self.checkBoxChest)
        self.checkBoxBack = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBoxBack.setEnabled(False)
        self.checkBoxBack.setObjectName(_fromUtf8("checkBoxBack"))
        self.verticalLayout_2.addWidget(self.checkBoxBack)
        self.checkBoxBiscep = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBoxBiscep.setEnabled(False)
        self.checkBoxBiscep.setObjectName(_fromUtf8("checkBoxBiscep"))
        self.verticalLayout_2.addWidget(self.checkBoxBiscep)
        self.checkTricep = QtGui.QCheckBox(self.layoutWidget5)
        self.checkTricep.setEnabled(False)
        self.checkTricep.setObjectName(_fromUtf8("checkTricep"))
        self.verticalLayout_2.addWidget(self.checkTricep)
        self.checkBoxLegs = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBoxLegs.setEnabled(False)
        self.checkBoxLegs.setObjectName(_fromUtf8("checkBoxLegs"))
        self.verticalLayout_2.addWidget(self.checkBoxLegs)
        self.checkBoxCore = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBoxCore.setEnabled(False)
        self.checkBoxCore.setObjectName(_fromUtf8("checkBoxCore"))
        self.verticalLayout_2.addWidget(self.checkBoxCore)
        self.checkBoxShoulders = QtGui.QCheckBox(self.layoutWidget5)
        self.checkBoxShoulders.setEnabled(False)
        self.checkBoxShoulders.setObjectName(_fromUtf8("checkBoxShoulders"))
        self.verticalLayout_2.addWidget(self.checkBoxShoulders)
        self.pushButtonCreateCancel = QtGui.QPushButton(self.CreatePlanWindow)
        self.pushButtonCreateCancel.setGeometry(QtCore.QRect(470, 390, 75, 23))
        self.pushButtonCreateCancel.setObjectName(_fromUtf8("pushButtonCreateCancel"))
        self.label_CreateValidation = QtGui.QLabel(self.CreatePlanWindow)
        self.label_CreateValidation.setGeometry(QtCore.QRect(240, 450, 311, 16))
        self.label_CreateValidation.setText(_fromUtf8(""))
        self.label_CreateValidation.setObjectName(_fromUtf8("label_CreateValidation"))
        self.stackedWidget.addWidget(self.CreatePlanWindow)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.tabWidget = QtGui.QTabWidget(self.page)
        self.tabWidget.setGeometry(QtCore.QRect(3, 22, 781, 511))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.label_15 = QtGui.QLabel(self.tab1)
        self.label_15.setGeometry(QtCore.QRect(90, 10, 331, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.labelWorkoutName = QtGui.QLabel(self.tab1)
        self.labelWorkoutName.setGeometry(QtCore.QRect(70, 110, 281, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelWorkoutName.setFont(font)
        self.labelWorkoutName.setObjectName(_fromUtf8("labelWorkoutName"))
        self.pushButtonSave1 = QtGui.QPushButton(self.tab1)
        self.pushButtonSave1.setGeometry(QtCore.QRect(80, 310, 91, 23))
        self.pushButtonSave1.setObjectName(_fromUtf8("pushButtonSave1"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab1)
        self.layoutWidget_3.setGeometry(QtCore.QRect(70, 180, 113, 111))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.layoutWidget_3)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.labelWeight = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.labelWeight.setFont(font)
        self.labelWeight.setObjectName(_fromUtf8("labelWeight"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelWeight)
        self.lineEditWeight_2 = QtGui.QLineEdit(self.layoutWidget_3)
        self.lineEditWeight_2.setObjectName(_fromUtf8("lineEditWeight_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditWeight_2)
        self.label_16 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.lineEditSet1 = QtGui.QLineEdit(self.layoutWidget_3)
        self.lineEditSet1.setObjectName(_fromUtf8("lineEditSet1"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditSet1)
        self.label_17 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_17)
        self.lineEditSet2 = QtGui.QLineEdit(self.layoutWidget_3)
        self.lineEditSet2.setObjectName(_fromUtf8("lineEditSet2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditSet2)
        self.label_18 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_18)
        self.lineEditSet3 = QtGui.QLineEdit(self.layoutWidget_3)
        self.lineEditSet3.setObjectName(_fromUtf8("lineEditSet3"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditSet3)
        self.Picture = QtGui.QLabel(self.tab1)
        self.Picture.setGeometry(QtCore.QRect(250, 90, 360, 351))
        self.Picture.setObjectName(_fromUtf8("Picture"))
        self.label_tab1Val = QtGui.QLabel(self.tab1)
        self.label_tab1Val.setGeometry(QtCore.QRect(70, 360, 191, 20))
        self.label_tab1Val.setText(_fromUtf8(""))
        self.label_tab1Val.setObjectName(_fromUtf8("label_tab1Val"))
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.labelWorkoutName_2 = QtGui.QLabel(self.tab_2)
        self.labelWorkoutName_2.setGeometry(QtCore.QRect(70, 110, 281, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelWorkoutName_2.setFont(font)
        self.labelWorkoutName_2.setObjectName(_fromUtf8("labelWorkoutName_2"))
        self.layoutWidget_4 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(70, 180, 113, 111))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.layoutWidget_4)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.labelWeight_2 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.labelWeight_2.setFont(font)
        self.labelWeight_2.setObjectName(_fromUtf8("labelWeight_2"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelWeight_2)
        self.lineEditWeight_3 = QtGui.QLineEdit(self.layoutWidget_4)
        self.lineEditWeight_3.setObjectName(_fromUtf8("lineEditWeight_3"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditWeight_3)
        self.label_19 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_19)
        self.lineEditSet1_2 = QtGui.QLineEdit(self.layoutWidget_4)
        self.lineEditSet1_2.setObjectName(_fromUtf8("lineEditSet1_2"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditSet1_2)
        self.label_20 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_20)
        self.lineEditSet2_2 = QtGui.QLineEdit(self.layoutWidget_4)
        self.lineEditSet2_2.setObjectName(_fromUtf8("lineEditSet2_2"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditSet2_2)
        self.label_21 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_21)
        self.lineEditSet3_2 = QtGui.QLineEdit(self.layoutWidget_4)
        self.lineEditSet3_2.setObjectName(_fromUtf8("lineEditSet3_2"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditSet3_2)
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(90, 10, 331, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.pushButtonSave2 = QtGui.QPushButton(self.tab_2)
        self.pushButtonSave2.setGeometry(QtCore.QRect(80, 310, 91, 23))
        self.pushButtonSave2.setObjectName(_fromUtf8("pushButtonSave2"))
        self.Picture_2 = QtGui.QLabel(self.tab_2)
        self.Picture_2.setGeometry(QtCore.QRect(250, 90, 360, 351))
        self.Picture_2.setObjectName(_fromUtf8("Picture_2"))
        self.label_tab2Val = QtGui.QLabel(self.tab_2)
        self.label_tab2Val.setGeometry(QtCore.QRect(60, 350, 191, 20))
        self.label_tab2Val.setText(_fromUtf8(""))
        self.label_tab2Val.setObjectName(_fromUtf8("label_tab2Val"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.labelWorkoutName_3 = QtGui.QLabel(self.tab_3)
        self.labelWorkoutName_3.setGeometry(QtCore.QRect(70, 110, 281, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelWorkoutName_3.setFont(font)
        self.labelWorkoutName_3.setObjectName(_fromUtf8("labelWorkoutName_3"))
        self.layoutWidget_5 = QtGui.QWidget(self.tab_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(70, 180, 113, 111))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.layoutWidget_5)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.labelWeight_3 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.labelWeight_3.setFont(font)
        self.labelWeight_3.setObjectName(_fromUtf8("labelWeight_3"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelWeight_3)
        self.lineEditWeight_4 = QtGui.QLineEdit(self.layoutWidget_5)
        self.lineEditWeight_4.setObjectName(_fromUtf8("lineEditWeight_4"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditWeight_4)
        self.label_23 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_23)
        self.lineEditSet1_3 = QtGui.QLineEdit(self.layoutWidget_5)
        self.lineEditSet1_3.setObjectName(_fromUtf8("lineEditSet1_3"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditSet1_3)
        self.label_24 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_24)
        self.lineEditSet2_3 = QtGui.QLineEdit(self.layoutWidget_5)
        self.lineEditSet2_3.setObjectName(_fromUtf8("lineEditSet2_3"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditSet2_3)
        self.label_25 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_25)
        self.lineEditSet3_3 = QtGui.QLineEdit(self.layoutWidget_5)
        self.lineEditSet3_3.setObjectName(_fromUtf8("lineEditSet3_3"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditSet3_3)
        self.label_26 = QtGui.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(90, 10, 331, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.pushButtonSave3 = QtGui.QPushButton(self.tab_3)
        self.pushButtonSave3.setGeometry(QtCore.QRect(80, 310, 91, 23))
        self.pushButtonSave3.setObjectName(_fromUtf8("pushButtonSave3"))
        self.Picture_3 = QtGui.QLabel(self.tab_3)
        self.Picture_3.setGeometry(QtCore.QRect(250, 130, 481, 251))
        self.Picture_3.setObjectName(_fromUtf8("Picture_3"))
        self.label_tab3Val = QtGui.QLabel(self.tab_3)
        self.label_tab3Val.setGeometry(QtCore.QRect(60, 350, 191, 20))
        self.label_tab3Val.setText(_fromUtf8(""))
        self.label_tab3Val.setObjectName(_fromUtf8("label_tab3Val"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.label_27 = QtGui.QLabel(self.page_2)
        self.label_27.setGeometry(QtCore.QRect(80, 50, 231, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.line_2 = QtGui.QFrame(self.page_2)
        self.line_2.setGeometry(QtCore.QRect(-10, 120, 791, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.progressBar = QtGui.QProgressBar(self.page_2)
        self.progressBar.setGeometry(QtCore.QRect(330, 180, 221, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.pushButtonStatsBack = QtGui.QPushButton(self.page_2)
        self.pushButtonStatsBack.setGeometry(QtCore.QRect(660, 500, 75, 23))
        self.pushButtonStatsBack.setObjectName(_fromUtf8("pushButtonStatsBack"))
        self.label_28 = QtGui.QLabel(self.page_2)
        self.label_28.setGeometry(QtCore.QRect(50, 160, 251, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(25)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.tableWidget = QtGui.QTableWidget(self.page_2)
        self.tableWidget.setGeometry(QtCore.QRect(100, 250, 461, 192))
        self.tableWidget.setFrameShape(QtGui.QFrame.HLine)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        PyFitness.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PyFitness)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        PyFitness.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PyFitness)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PyFitness.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(PyFitness)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(PyFitness)
        self.stackedWidget.setCurrentIndex(4)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL(_fromUtf8("triggered()")), PyFitness.close)
        QtCore.QMetaObject.connectSlotsByName(PyFitness)

    def retranslateUi(self, PyFitness):
        PyFitness.setWindowTitle(_translate("PyFitness", "PyFitness", None))
        self.label_3.setText(_translate("PyFitness", "Fitness App", None))
        self.label.setText(_translate("PyFitness", "Enter User:        ", None))
        self.label_2.setText(_translate("PyFitness", "Enter Password:", None))
        self.pushButton_2.setText(_translate("PyFitness", "Sign Up!", None))
        self.pushButton.setText(_translate("PyFitness", "Login", None))
        self.label_4.setText(_translate("PyFitness", "First Name:", None))
        self.label_5.setText(_translate("PyFitness", "Last Name:", None))
        self.label_6.setText(_translate("PyFitness", "Username:", None))
        self.label_9.setText(_translate("PyFitness", "Password:", None))
        self.label_8.setText(_translate("PyFitness", "Age:", None))
        self.label_7.setText(_translate("PyFitness", "Weight:", None))
        self.pushButtonSignUp.setText(_translate("PyFitness", "Sign Up!", None))
        self.pushButtonCancel.setText(_translate("PyFitness", "Cancel", None))
        self.label_10.setText(_translate("PyFitness", "Fitness App", None))
        self.label_29.setText(_translate("PyFitness", "Create Plan", None))
        self.label_30.setText(_translate("PyFitness", "Start Plan", None))
        self.label_31.setText(_translate("PyFitness", "View Progress", None))
        self.radioButtonPlan.setText(_translate("PyFitness", "3 Day Plan", None))
        self.label_12.setText(_translate("PyFitness", "Day 3:", None))
        self.checkBoxChest_3.setText(_translate("PyFitness", "Chest", None))
        self.checkBoxBack_3.setText(_translate("PyFitness", "Back", None))
        self.checkBoxBiscep_3.setText(_translate("PyFitness", "Biscep", None))
        self.checkTricep_3.setText(_translate("PyFitness", "Tricep", None))
        self.checkBoxLegs_3.setText(_translate("PyFitness", "Legs", None))
        self.checkBoxCore_3.setText(_translate("PyFitness", "Core(abs)", None))
        self.checkBoxShoulders_3.setText(_translate("PyFitness", "Shoulders", None))
        self.label_13.setText(_translate("PyFitness", "Day 2:", None))
        self.checkBoxChest_2.setText(_translate("PyFitness", "Chest", None))
        self.checkBoxBack_2.setText(_translate("PyFitness", "Back", None))
        self.checkBoxBiscep_2.setText(_translate("PyFitness", "Biscep", None))
        self.checkTricep_2.setText(_translate("PyFitness", "Tricep", None))
        self.checkBoxLegs_2.setText(_translate("PyFitness", "Legs", None))
        self.checkBoxCore_2.setText(_translate("PyFitness", "Core(abs)", None))
        self.checkBoxShoulders_2.setText(_translate("PyFitness", "Shoulders", None))
        self.label_14.setText(_translate("PyFitness", "Plan Length:", None))
        self.pushButtonSubmit.setText(_translate("PyFitness", "Submit", None))
        self.label_11.setText(_translate("PyFitness", "Day 1:", None))
        self.checkBoxChest.setText(_translate("PyFitness", "Chest", None))
        self.checkBoxBack.setText(_translate("PyFitness", "Back", None))
        self.checkBoxBiscep.setText(_translate("PyFitness", "Biscep", None))
        self.checkTricep.setText(_translate("PyFitness", "Tricep", None))
        self.checkBoxLegs.setText(_translate("PyFitness", "Legs", None))
        self.checkBoxCore.setText(_translate("PyFitness", "Core(abs)", None))
        self.checkBoxShoulders.setText(_translate("PyFitness", "Shoulders", None))
        self.pushButtonCreateCancel.setText(_translate("PyFitness", "Cancel", None))
        self.label_15.setText(_translate("PyFitness", "Do 3 sets of as many reps as you can.", None))
        self.labelWorkoutName.setText(_translate("PyFitness", "Workout Name", None))
        self.pushButtonSave1.setText(_translate("PyFitness", "Save Progress", None))
        self.labelWeight.setText(_translate("PyFitness", "Weight:", None))
        self.label_16.setText(_translate("PyFitness", "Set 1: ", None))
        self.label_17.setText(_translate("PyFitness", "Set 2: ", None))
        self.label_18.setText(_translate("PyFitness", "Set 3:", None))
        self.Picture.setText(_translate("PyFitness", "l", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("PyFitness", "Workout 1", None))
        self.labelWorkoutName_2.setText(_translate("PyFitness", "Workout Name", None))
        self.labelWeight_2.setText(_translate("PyFitness", "Weight:", None))
        self.label_19.setText(_translate("PyFitness", "Set 1: ", None))
        self.label_20.setText(_translate("PyFitness", "Set 2: ", None))
        self.label_21.setText(_translate("PyFitness", "Set 3:", None))
        self.label_22.setText(_translate("PyFitness", "Do 3 sets of as many reps as you can.", None))
        self.pushButtonSave2.setText(_translate("PyFitness", "Save Progress", None))
        self.Picture_2.setText(_translate("PyFitness", "l", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PyFitness", "Workout 2", None))
        self.labelWorkoutName_3.setText(_translate("PyFitness", "Workout Name", None))
        self.labelWeight_3.setText(_translate("PyFitness", "Weight:", None))
        self.label_23.setText(_translate("PyFitness", "Set 1: ", None))
        self.label_24.setText(_translate("PyFitness", "Set 2: ", None))
        self.label_25.setText(_translate("PyFitness", "Set 3:", None))
        self.label_26.setText(_translate("PyFitness", "Do 3 sets of as many reps as you can.", None))
        self.pushButtonSave3.setText(_translate("PyFitness", "Save Progress", None))
        self.Picture_3.setText(_translate("PyFitness", "l", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PyFitness", "Workout 3", None))
        self.label_27.setText(_translate("PyFitness", "Statistics", None))
        self.pushButtonStatsBack.setText(_translate("PyFitness", "Back", None))
        self.label_28.setText(_translate("PyFitness", "Workout Progress:", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("PyFitness", "Workout Name", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("PyFitness", "Start Weight", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("PyFitness", "Current Weight", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("PyFitness", "Average Reps", None))
        self.menuFile.setTitle(_translate("PyFitness", "File", None))
        self.actionClose.setText(_translate("PyFitness", "Close", None))

